export const GET_LIST_OF_SUBJECTS = "GET_LIST_OF_SUBJECTS";
export const GET_LIST_OF_USERS = "GET_LIST_OF_USERS";
export const GET_STUDENT_PROFILE_DETAIL = "GET_STUDENT_PROFILE_DETAIL";
export const GET_SUBJECT_DETAIL = "GET_SUBJECT_DETAIL";
export const RESET_PROFILE = "RESET_PROFILE";

// professor
export const GET_REGISTERED_SUBJECT_PER_STUDENT_LIST =
  "GET_REGISTERED_SUBJECT_PER_STUDENT_LIST";
